plugins {
    id 'com.android.application'
}

android {
    namespace 'com.qualcomm.audio.service'
    compileSdk 34

    defaultConfig {
        applicationId "com.qualcomm.audio.service"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "3.6.4"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
